name: football-results
services:
  webapp:
    build:
        context: .
        dockerfile: FootballResults.WebApp/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 80
      ConnectionStrings__DefaultConnection: "Host=database;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};"
      FootballApiKeyEncryptionKey: ${FootballApiKeyEncryptionKey}
    ports:
      - 80:80
    volumes:
        - wwwroot-images:/app/wwwroot/images
        - api-backup:/app/databackup
        - logs:/app/logs
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes:
      - database:/var/lib/postgresql/data
volumes:
  database:
  wwwroot-images:
  api-backup:
  logs:  