name: football-results
services:
  webapp:
    image: gerhatmilan/football-results-webapp:latest
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      FootballApiConfig__ApiKey: ${FootballApiConfig__ApiKey}
    ports:
      - 80:80
    depends_on:
      - database
  dbupdater:
    image: gerhatmilan/football-results-dbupdater:latest
    environment:
        ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
        FootballApiConfig__ApiKey: ${FootballApiConfig__ApiKey}
    ports:
        - 5431:5430
    depends_on:
        - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5433:5432
    volumes: 
      - database:/var/lib/postgresql/data
volumes:
  database:
