name: footballresults
services:
  webapp:
    build:
      context: .
      dockerfile: FootballResults.WebApp/Dockerfile
    environment:
      ASPNETCORE_HTTP_PORTS: 80
      ConnectionStrings__DefaultConnection: ${ConnectionStrings__DefaultConnection}
      FootballApiConfig__ApiKey: ${FootballApiConfig__ApiKey}
    ports:
      - 80:80
    depends_on:
      - database
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes: 
      - database:/var/lib/postgresql/data
volumes:
  database:
